const CONSTANT = {
  BUTTON: {
    MARGIN: 14,
    FONT_SIZE: 16,
    FONT_WEIGHT: '500',
    ICON_TITLE_MARGIN_HORIZONTAL: 2,
  },
  INPUT: {
    PADDING_VERTICAL: 14,
    PADDING_HORIZONTAL: 16,
    FONT_SIZE: 16,
    FONT_WEIGHT: '500',
    ICON_TITLE_MARGIN_HORIZONTAL: 4,
    TITLE_MARGIN_BOTTOM: 4,
    TITLE_FONT_SIZE: 16,
    ERROR_MARGIN_TOP: 4,
    ERROR_FONT_SIZE: 12,
  },
  LIST_REQUEST: {
    PAGE_SIZE: 10,
  },
};

export default CONSTANT;
