name: Ping Release

on:
  push:
    branches: [ production ]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/longly151/RNDeployBase/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PING_ACCESS_TOKEN }} \
          --data '{"event_type": "RNBase_ping_release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ping_access_token": "PING_ACCESS_TOKEN", "env": "RNBASE_ENV_PRODUCTION", "fastlane_android_env": "RNBASE_FASTLANE_ANDROID_ENV", "fastlane_ios_env": "RNBASE_FASTLANE_IOS_ENV" }}'